twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        TELEGRAM_BOT_URL: '%env(TELEGRAM_BOT_URL)%'

when@test:
    twig:
        strict_variables: true
