<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Infrastructure\Doctrine\Type\ReminderChannelTypeEnumType;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240803212141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TYPE ' . ReminderChannelTypeEnumType::NAME . ' AS ENUM(\'telegram\')');
        $this->addSql('CREATE TABLE reminders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, repeat_period INT NOT NULL, channel_type ' . ReminderChannelTypeEnumType::NAME . ' NOT NULL, channel_id VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE reminder_exercises (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reminder_id INT NOT NULL, question VARCHAR(255) NOT NULL, answer VARCHAR(255) NOT NULL, correct_answer VARCHAR(255) NOT NULL, is_completed BOOLEAN NOT NULL, is_right BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN reminders.repeat_period IS \'Период повтора в минутах\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE reminders');
        $this->addSql('DROP TABLE reminder_exercises');
        $this->addSql('DROP TYPE ' . ReminderChannelTypeEnumType::NAME . '');
    }
}
