<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Infrastructure\Doctrine\Type\ExaminationEnumType;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240801180010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TYPE ' . ExaminationEnumType::NAME . ' AS ENUM(\'exam\', \'train\')');
        $this->addSql('CREATE TABLE examinations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type ' . ExaminationEnumType::NAME . ' NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE exercises (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, examination_id INT NOT NULL, question VARCHAR(255) NOT NULL, answer VARCHAR(255) NOT NULL, correct_answer VARCHAR(255) NOT NULL, is_completed BOOLEAN NOT NULL, is_right BOOLEAN NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE examinations');
        $this->addSql('DROP TABLE exercises');
        $this->addSql('DROP TYPE ' . ExaminationEnumType::NAME . '');
    }
}
