version: "3"

server:
    command: "php public/index.php"
    env:
        -   APP_RUNTIME: FluffyDiscord\RoadRunnerBundle\Runtime\Runtime
http:
    address: :${APP_PORT}
    pool:
        num_workers: 4
        max_jobs: 64
    middleware: [ "gzip", "static" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]

